# Generated by Django 5.0.2 on 2024-05-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tags_order_customer_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_entered',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_entered',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_entered',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
